{% set name = "tflite-support" %}
{% set version = "0.3.0" %}
{% set tf_version_maj_min = "2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/{{name}}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e12967ddbe993ee7b92d4721a3b1c04e9cbbf6ca10c3a3b4a08bd6094daf59f1
  patches:


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - bazel
    - bazel-toolchain
    - grpc-cpp
    - libprotobuf
    - nasm
    - rsync
    - sed
    - setuptools
  host:
    # GPU requirements for CUDA
    - cudnn           # [cuda_compiler_version != "None"]
    - python
    - pip
    - libprotobuf
    - protobuf >=3.9.2


  run:
    - python
    - absl-py >= 0.7.0
    - numpy >= 1.19.2
    - flatbuffers >= 1.12, <2

test:
  requires:
    - pip
  imports:
    - tflite-support
  commands:
    - pip check

about:
  home: https://github.com/tensorflow/tflite-support
  license: Apache-2.0
  license_file: LICENSE
  summary: TFLite Support is a toolkit that helps users to develop ML and deploy TFLite models onto mobile devices. 
  dev_url: https://github.com/tensorflow/tflite-support

extra:
  recipe-maintainers:
    - mxr-conda
    - AdMax18
