{% set name = "note_seq" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/py3/n/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: 4d2aec0fa42e182bbc27ed5a192b2f9bd6307c8177794bb8e8b582d0601e1797

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed {{ name }}-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - note-seq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://magenta.tensorflow.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Use machine learning to create art and music"

extra:
  recipe-maintainers:
    - mxr-conda
    - AdMax18
