{% set name = "pyobjc-framework-ApplicationServices" %}
{% set version = "8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobjc-framework-ApplicationServices-{{ version }}.tar.gz
  sha256: 01b8378cd27bbc2bad449600a5ff05060cd4f2098eb6b7bc85f0f95baad721b6

build:
  number: 0
  skip: true   # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - pyobjc-core >=8.1
    - pyobjc-framework-cocoa >=8.1
    - pyobjc-framework-quartz >=8.1
    - python

test:
  imports:
    - ApplicationServices
    - HIServices
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework ApplicationServices on macOS
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - admax18
    - mxr-conda
